Traceback (most recent call last):
  File "test/verify/check-kdump", line *, in testBasic
    m.wait_boot(timeout_sec=300)
*
machine_core.exceptions.Failure: Unable to reach machine *
