Traceback (most recent call last):
  File "test/machineslib.py", line *, in tearDown
    super().tearDown()
*
  File "test/common/testlib.py", line *, in tearDown
    self.check_journal_messages()
*
  File "test/common/testlib.py", line *, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process * (libvirtd) of user * terminated abnormally with signal 11/SEGV, processing...
